sudo: required
dist: xenial
language: rust
rust:
  - nightly
  
cache:
  cargo: true
  apt: true

matrix:
  allow_failures:
    - rust: nightly
    
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
    
env:
  global:
    # - RUSTFLAGS="-C link-dead-code"
    - OPENSSL_VERSION=openssl-1.0.2
    - DATABASE_URL=postgres://nvidia:nvidia@localhost/block_chain
    - CUDA=10.0.130-1
    - CUDA=8.0.61-1

before_install:
  # - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev
